@baseUrl = http://localhost:4000

# @name login
POST {{baseUrl}}/api/auth
Content-Type: application/json

{
    "username":"tom2",
    "password":"password",
    "email":"tom2@example.com",
    "confirmPassword":"password",
    "unknown":"oh no"
}
